"""Tests for Rust TLS build configuration task."""
import subprocess
import re
import os
import pathlib

def test_cargo_build_succeeds():
    """Verify cargo build completes successfully."""
    result = subprocess.run(
        ["cargo", "build", "--release"],
        cwd="/app",
        capture_output=True,
        text=True
    )
    assert result.returncode == 0, f"Build failed: {result.stderr}"

def test_bindgen_generated_bindings():
    """Anti-cheat: Verify bindgen actually generated bindings."""
    build_dir = pathlib.Path("/app/target/release/build")
    assert build_dir.exists(), "Build directory not found"
    
    # Find bindings.rs files generated by bindgen
    bindings_files = list(build_dir.rglob("bindings.rs"))
    assert len(bindings_files) > 0, "bindgen did not generate bindings.rs files"

def test_binary_linked_against_openssl():
    """Anti-cheat: Verify binary is actually linked against OpenSSL."""
    binary_path = "/app/target/release/examples/https_client"
    if not os.path.exists(binary_path):
        binary_path = "/app/target/release/https_client"
    
    assert os.path.exists(binary_path), "Binary not found"
    
    # Check library dependencies using ldd if available
    try:
        result = subprocess.run(
            ["ldd", binary_path],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            output = result.stdout
            assert "libssl" in output or "libcrypto" in output, \
                "Binary not linked against OpenSSL libraries"
    except (subprocess.TimeoutExpired, FileNotFoundError):
        # ldd not available, skip this check
        pass

def test_openssl_libraries_exist():
    """Anti-cheat: Verify OpenSSL libraries exist in expected location."""
    openssl_lib_dir = pathlib.Path("/opt/openssl/lib")
    assert openssl_lib_dir.exists(), "OpenSSL lib directory not found"
    
    # Check for libssl
    libssl_files = list(openssl_lib_dir.glob("libssl.so*"))
    assert len(libssl_files) > 0, "libssl.so not found in /opt/openssl/lib"
    
    # Check for libcrypto
    libcrypto_files = list(openssl_lib_dir.glob("libcrypto.so*"))
    assert len(libcrypto_files) > 0, "libcrypto.so not found in /opt/openssl/lib"

def test_llvm_14_installed():
    """Anti-cheat: Verify LLVM 14 is installed (not just 13 or 15)."""
    llvm14_paths = [
        "/usr/lib/llvm-14",
        "/usr/lib/x86_64-linux-gnu/llvm-14"
    ]
    assert any(os.path.exists(p) for p in llvm14_paths), \
        "LLVM 14 not found - incorrect version may have been used"

def test_https_client_runs():
    """Verify HTTPS client example executes successfully."""
    result = subprocess.run(
        ["cargo", "run", "--release", "--example", "https_client"],
        cwd="/app",
        capture_output=True,
        text=True,
        timeout=30
    )
    assert result.returncode == 0, f"Example failed: {result.stderr}"
    return result.stdout + result.stderr

def test_tls_connection_established():
    """Verify TLS connection was successfully established."""
    output = test_https_client_runs()
    assert "Successfully connected to https://www.rust-lang.org" in output, \
        "Success message not found in output"

def test_tls_version_valid():
    """Verify TLS version is 1.2 or higher."""
    output = test_https_client_runs()
    tls_match = re.search(r"TLS version: TLSv1\.([23])", output)
    assert tls_match is not None, "Valid TLS version not found in output"

def test_real_http_response():
    """Anti-cheat: Verify actual HTTP response was received (not just printed strings)."""
    output = test_https_client_runs()
    # The output should contain actual response data, not just success messages
    # This ensures a real TLS connection was made
    assert len(output) > 50, "Output too short - may not be from real connection"

def test_pkg_config_files_created():
    """Anti-cheat: Verify pkg-config files were created for OpenSSL."""
    openssl_pc = pathlib.Path("/opt/openssl/lib/pkgconfig/openssl.pc")
    assert openssl_pc.exists(), "pkg-config file for OpenSSL not found - OpenSSL may not be properly configured"
